[package]
name = "emailio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
email_address = "0.2.4"
serde = "1.0.147"
thiserror = "1.0.37"

[dev-dependencies]
serde_json = "1.0.88"
